// <auto-generated />
namespace JedjanguiWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pret : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pret));
        
        string IMigrationMetadata.Id
        {
            get { return "201805061618274_pret"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
