//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JedjanguiWeb.Resources.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Traduction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Traduction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JedjanguiWeb.Resources.Model.Traduction", typeof(Traduction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresse.
        /// </summary>
        public static string Addresse {
            get {
                return ResourceManager.GetString("Addresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banque.
        /// </summary>
        public static string Banque {
            get {
                return ResourceManager.GetString("Banque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But.
        /// </summary>
        public static string But {
            get {
                return ResourceManager.GetString("But", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte Bancaire.
        /// </summary>
        public static string CompteBanque {
            get {
                return ResourceManager.GetString("CompteBanque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;adhesion.
        /// </summary>
        public static string DateAdhession {
            get {
                return ResourceManager.GetString("DateAdhession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter le.
        /// </summary>
        public static string DateAjouter {
            get {
                return ResourceManager.GetString("DateAjouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de creation.
        /// </summary>
        public static string DateCreation {
            get {
                return ResourceManager.GetString("DateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de Debut.
        /// </summary>
        public static string DateDebut {
            get {
                return ResourceManager.GetString("DateDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string DateFin {
            get {
                return ResourceManager.GetString("DateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de Naissance.
        /// </summary>
        public static string DateNaissance {
            get {
                return ResourceManager.GetString("DateNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debut de l&apos;exercice.
        /// </summary>
        public static string DebutExo {
            get {
                return ResourceManager.GetString("DebutExo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duree.
        /// </summary>
        public static string Duree {
            get {
                return ResourceManager.GetString("Duree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eloge.
        /// </summary>
        public static string Eloge {
            get {
                return ResourceManager.GetString("Eloge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de l&apos;exercice.
        /// </summary>
        public static string FinExo {
            get {
                return ResourceManager.GetString("FinExo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de saisie.
        /// </summary>
        public static string FinSaisie {
            get {
                return ResourceManager.GetString("FinSaisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Fonction {
            get {
                return ResourceManager.GetString("Fonction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interet.
        /// </summary>
        public static string Interet {
            get {
                return ResourceManager.GetString("Interet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Interest Precedent.
        /// </summary>
        public static string InteretAvant {
            get {
                return ResourceManager.GetString("InteretAvant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu de Reunion.
        /// </summary>
        public static string LieuRencontre {
            get {
                return ResourceManager.GetString("LieuRencontre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricule.
        /// </summary>
        public static string Matricule {
            get {
                return ResourceManager.GetString("Matricule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string Montant {
            get {
                return ResourceManager.GetString("Montant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant a rembourser.
        /// </summary>
        public static string MontantARembourser {
            get {
                return ResourceManager.GetString("MontantARembourser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant Precedent.
        /// </summary>
        public static string MontantAvant {
            get {
                return ResourceManager.GetString("MontantAvant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant Rembourse.
        /// </summary>
        public static string MontantRembourser {
            get {
                return ResourceManager.GetString("MontantRembourser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre d&apos;enfant.
        /// </summary>
        public static string NbEnfant {
            get {
                return ResourceManager.GetString("NbEnfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;exercice.
        /// </summary>
        public static string NomExo {
            get {
                return ResourceManager.GetString("NomExo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du Fond.
        /// </summary>
        public static string NomFond {
            get {
                return ResourceManager.GetString("NomFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste.
        /// </summary>
        public static string PosteExercice {
            get {
                return ResourceManager.GetString("PosteExercice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence.
        /// </summary>
        public static string Residence {
            get {
                return ResourceManager.GetString("Residence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigle.
        /// </summary>
        public static string Sigle {
            get {
                return ResourceManager.GetString("Sigle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slogan.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solde.
        /// </summary>
        public static string Solde {
            get {
                return ResourceManager.GetString("Solde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Statut {
            get {
                return ResourceManager.GetString("Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut Matrimoniale.
        /// </summary>
        public static string StatutMatrimoniale {
            get {
                return ResourceManager.GetString("StatutMatrimoniale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeFond {
            get {
                return ResourceManager.GetString("TypeFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider?.
        /// </summary>
        public static string Valider {
            get {
                return ResourceManager.GetString("Valider", resourceCulture);
            }
        }
    }
}
